In [1]:
import pandas as pd

In [2]:
files = ["ALQ_L", "BIOPRO_L", "BMX_L", "BPQ_L", "BPXO_L", "CBC_L", "DEMO_L", "DIQ_L", "FERTIN_L", "FOLFMS_L", "GHB_L", "HDL_L", "HSCRP_L", "SMQ_L", "TCHOL_L", "TRIGLY_L", "VID_L"]

datasets = {}

for file in files:
    path = f"../data/raw/{file}.xpt"
    datasets[file] = pd.read_sas(path)

    print(f"{file} loaded")

ALQ_L loaded
BIOPRO_L loaded
BMX_L loaded
BPQ_L loaded
BPXO_L loaded
CBC_L loaded
DEMO_L loaded
DIQ_L loaded
FERTIN_L loaded
FOLFMS_L loaded
GHB_L loaded
HDL_L loaded
HSCRP_L loaded
SMQ_L loaded
TCHOL_L loaded
TRIGLY_L loaded
VID_L loaded

In [3]:
datasets.keys()

dict_keys(['ALQ_L', 'BIOPRO_L', 'BMX_L', 'BPQ_L', 'BPXO_L', 'CBC_L', 'DEMO_L', 'DIQ_L', 'FERTIN_L', 'FOLFMS_L', 'GHB_L', 'HDL_L', 'HSCRP_L', 'SMQ_L', 'TCHOL_L', 'TRIGLY_L', 'VID_L'])

In [4]:
demo = datasets["DEMO_L"][["SEQN", "RIAGENDR", "RIDAGEYR", "RIDRETH3"  ]].rename(columns={"SEQN": "id", "RIAGENDR": "gender", "RIDAGEYR": "age", "RIDRETH3": "ethnicity"})
demo.head()

         id  gender   age  ethnicity
0  130378.0     1.0  43.0        6.0
1  130379.0     1.0  66.0        3.0
2  130380.0     2.0  44.0        2.0
3  130381.0     2.0   5.0        7.0
4  130382.0     1.0   2.0        3.0

In [5]:
demo.shape

(11933, 4)

In [6]:
cbc = datasets["CBC_L"][["SEQN", "LBXWBCSI", "LBDLYMNO", "LBDMONO", "LBDNENO", "LBXRBCSI", "LBXHGB", "LBXHCT", "LBXMCVSI", "LBXMC", "LBXMCHSI", "LBXRDW", "LBXPLTSI", "LBXMPSI"]].rename(columns={"SEQN": "id", "LBXWBCSI": "WBC (Abs.)", "LBDLYMNO": "Lymphocytes (Abs.)", "LBDMONO": "Monocytes (Abs.)", "LBDNENO": "Neutrophils (Abs.)", "LBXRBCSI": "RBC", "LBXHGB": "Haemoglobin (g/dL)", "LBXHCT": "HCT (%)", "LBXMCVSI": "MCV (fL)", "LBXMC": "MCHC(g/dL)", "LBXMCHSI": "MCH(pg)", "LBXRDW": "RDW(%)", "LBXPLTSI": "PLT(1000/μL)", "LBXMPSI": "MPV(fL)"})    
cbc.head()

,id,WBC (Abs.),Lymphocytes (Abs.),Monocytes (Abs.),Neutrophils (Abs.),RBC,Haemoglobin (g/dL),HCT (%),MCV (fL),MCHC(g/dL),MCH(pg),RDW(%),PLT(1000/μL),MPV(fL)
0,130378.0,4.7,1.9,0.3,2.2,5.19,15.7,45.3,87.4,34.6,30.2,12.9,259.0,7.8
1,130379.0,6.3,1.6,0.9,3.6,4.59,15.2,43.9,95.8,34.5,33.0,12.8,221.0,8.5
2,130380.0,5.7,1.7,0.3,3.3,4.86,13.8,40.1,82.5,34.4,28.3,13.3,235.0,9.1
3,130381.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,130382.0,11.4,3.4,0.9,6.9,4.61,12.3,36.5,79.2,33.6,26.7,14.6,342.0,7.4

In [7]:
cbc.shape

(8727, 14)

In [8]:
alcohol = datasets["ALQ_L"][["SEQN", "ALQ111", "ALQ121", "ALQ130", "ALQ142", "ALQ280"]].rename(columns={"SEQN": "id", "ALQ111": "Alc_consum?", "ALQ121": "Alc_<12M?", "ALQ130": "Avg_drink_day_12M", "ALQ142": "Days_+4_drinks", "ALQ280": "Days_+8_drinks?"})
alcohol.head()

,id,Alc_consum?,Alc_<12M?,Avg_drink_day_12M,Days_+4_drinks,Days_+8_drinks?
0,130378.0,NaN,NaN,NaN,NaN,NaN
1,130379.0,1.0,2.000000e+00,3.0,5.397605e-79,NaN
2,130380.0,1.0,1.000000e+01,1.0,5.397605e-79,NaN
3,130386.0,1.0,4.000000e+00,2.0,1.000000e+01,10.0
4,130387.0,1.0,5.397605e-79,NaN,NaN,NaN

In [9]:
biochem = datasets["BIOPRO_L"][["SEQN", "LBXSATSI", "LBDSALSI", "LBXSASSI", "LBDSGLSI", "LBXSGTSI", "LBDSIRSI", "LBXSTB", "LBDSCHSI", "LBDSTPSI", "LBDSTRSI", "LBDSUASI" ]].rename(columns={"SEQN": "id", "LBXSATSI": "ALT (IU/L)", "LBDSALSI": "Albumin (g/L)", "LBXSASSI": "AST (IU/L)", "LBDSGLSI": "Glucose (mmol/L)", "LBXSGTSI": "GGT (IU/L)", "LBDSIRSI": "Iron (μmol/L)", "LBXSTB": "Total_Bilirubin (μmol/L)", "LBDSCHSI": "Cholesterol (mmol/L)", "LBDSTPSI": "Total_Protein (g/L)", "LBDSTRSI": "Triglycerides (mmol/L)", "LBDSUASI": "Uric_Acid (μmol/L)"})
biochem.head()

,id,ALT (IU/L),Albumin (g/L),AST (IU/L),Glucose (mmol/L),GGT (IU/L),Iron (μmol/L),Total_Bilirubin (μmol/L),Cholesterol (mmol/L),Total_Protein (g/L),Triglycerides (mmol/L),Uric_Acid (μmol/L)
0,130378.0,39.0,43.0,25.0,6.0,41.0,18.0,0.7,6.89,75.0,1.73,303.3
1,130379.0,17.0,39.0,20.0,5.0,31.0,16.0,0.7,5.62,73.0,0.99,505.6
2,130380.0,13.0,37.0,15.0,8.0,44.0,24.0,0.6,4.74,76.0,4.24,261.7
3,130386.0,34.0,43.0,20.0,5.0,28.0,25.0,0.5,4.79,69.0,1.58,356.9
4,130387.0,12.0,37.0,13.0,6.0,17.0,8.0,0.3,5.26,67.0,1.25,368.8

In [10]:
biochem.shape

(7199, 12)

In [11]:
BMI = datasets["BMX_L"][["SEQN","BMXWT","BMXHT", "BMXBMI", "BMXWAIST", "BMXHIP"]].rename(columns={"SEQN": "id", "BMXWT": "Weight (kg)", "BMXHT": "Height (cm)", "BMXBMI": "BMI", "BMXWAIST": "Waist_Circumference (cm)", "BMXHIP": "Hip_Circumference (cm)"})
BMI.head()

,id,Weight (kg),Height (cm),BMI,Waist_Circumference (cm),Hip_Circumference (cm)
0,130378.0,86.9,179.5,27.0,98.3,102.9
1,130379.0,101.8,174.2,33.5,114.7,112.4
2,130380.0,69.4,152.9,29.7,93.5,98.0
3,130381.0,34.3,120.1,23.8,70.4,NaN
4,130382.0,13.6,NaN,NaN,NaN,NaN

In [12]:
BMI.shape

(8860, 6)

In [13]:
blood_pressure = datasets["BPQ_L"][["SEQN", "BPQ020", "BPQ150", "BPQ080", "BPQ101D"]].rename(columns={"SEQN": "id", "BPQ020": "Ever_told_high_BP?", "BPQ150": "BP_medication?", "BPQ080": "high_cholesterol?", "BPQ101D": "cholesterol_medication?"})
blood_pressure.head()

,id,Ever_told_high_BP?,BP_medication?,high_cholesterol?,cholesterol_medication?
0,130378.0,1.0,1.0,2.0,2.0
1,130379.0,1.0,1.0,2.0,2.0
2,130380.0,2.0,NaN,1.0,1.0
3,130384.0,2.0,NaN,2.0,2.0
4,130385.0,2.0,NaN,2.0,2.0

In [14]:
bp_readings = datasets["BPXO_L"][["SEQN", "BPXOSY1", "BPXODI1", "BPXOSY2", "BPXODI2", "BPXOSY3", "BPXODI3", "BPXOPLS1", "BPXOPLS2", "BPXOPLS3"]].rename(columns={"SEQN": "id", "BPXOSY1": "Systolic_BP_1(mmHg)", "BPXODI1": "Diastolic_BP_1(mmHg)", "BPXOSY2": "Systolic_BP_2(mmHg)", "BPXODI2": "Diastolic_BP_2(mmHg)", "BPXOSY3": "Systolic_BP_3(mmHg)", "BPXODI3": "Diastolic_BP_3(mmHg)", "BPXOPLS1": "Pulse_1", "BPXOPLS2": "Pulse_2", "BPXOPLS3": "Pulse_3"})
bp_readings.head()

,id,Systolic_BP_1(mmHg),Diastolic_BP_1(mmHg),Systolic_BP_2(mmHg),Diastolic_BP_2(mmHg),Systolic_BP_3(mmHg),Diastolic_BP_3(mmHg),Pulse_1,Pulse_2,Pulse_3
0,130378.0,135.0,98.0,131.0,96.0,132.0,94.0,82.0,79.0,82.0
1,130379.0,121.0,84.0,117.0,76.0,113.0,76.0,72.0,71.0,73.0
2,130380.0,111.0,79.0,112.0,80.0,104.0,76.0,84.0,83.0,77.0
3,130386.0,110.0,72.0,120.0,74.0,115.0,75.0,59.0,64.0,64.0
4,130387.0,143.0,76.0,136.0,74.0,145.0,78.0,80.0,80.0,77.0

In [15]:
bp_readings.shape

(7801, 10)

In [16]:
diabetes = datasets["DIQ_L"][["SEQN", "DIQ010", "DID040", "DIQ160", "DIQ050", "DIQ070"]].rename(columns={"SEQN": "id", "DIQ010": "Ever_told_diabetes?", "DID040": "Age_Diabetes", "DIQ160": "Ever_told_pre-diabetes?", "DIQ050": "Insulin?", "DIQ070": "Diabetes_medication?"})
diabetes.head()

,id,Ever_told_diabetes?,Age_Diabetes,Ever_told_pre-diabetes?,Insulin?,Diabetes_medication?
0,130378.0,2.0,NaN,2.0,NaN,NaN
1,130379.0,2.0,NaN,2.0,NaN,NaN
2,130380.0,1.0,35.0,NaN,2.0,1.0
3,130381.0,2.0,NaN,NaN,NaN,NaN
4,130382.0,2.0,NaN,NaN,NaN,NaN

In [17]:
diabetes.shape

(11744, 6)

In [18]:
ferritin = datasets["FERTIN_L"][["SEQN", "LBDFERSI"]].rename(columns={"SEQN": "id", "LBDFERSI": "Ferritin (ng/mL)"})
ferritin.head()

         id  Ferritin (ng/mL)
0  130380.0              13.3
1  130381.0               NaN
2  130382.0              24.4
3  130388.0               NaN
4  130390.0              52.1

In [19]:
ferritin.shape

(2564, 2)

In [20]:
folate = datasets["FOLFMS_L"][["SEQN", "LBDFOTSI"]].rename(columns={"SEQN": "id", "LBDFOTSI": "Folate (nmol/L)"})
folate.head()

         id  Folate (nmol/L)
0  130378.0             14.1
1  130379.0             24.3
2  130380.0             25.1
3  130381.0              NaN
4  130382.0             70.5

In [21]:
folate.shape

(8727, 2)

In [22]:
hba1c = datasets["GHB_L"][["SEQN", "LBXGH"]].rename(columns={"SEQN": "id", "LBXGH": "HbA1c (%)"})
hba1c.head()

         id  HbA1c (%)
0  130378.0        5.6
1  130379.0        5.6
2  130380.0        6.2
3  130386.0        5.1
4  130387.0        5.9

In [23]:
hba1c.shape

(7199, 2)

In [24]:
HDL = datasets["HDL_L"][["SEQN", "LBDHDDSI"]].rename(columns={"SEQN": "id", "LBDHDDSI": "HDL (mmol/L)"})
HDL.head()

         id  HDL (mmol/L)
0  130378.0          1.16
1  130379.0          1.55
2  130380.0          1.27
3  130386.0          1.19
4  130387.0          1.09

In [25]:
HDL.shape

(8068, 2)

In [26]:
CRP = datasets["HSCRP_L"][["SEQN", "LBXHSCRP"]].rename(columns={"SEQN": "id", "LBXHSCRP": "CRP (mg/L)"})
CRP.head()

         id  CRP (mg/L)
0  130378.0        1.78
1  130379.0        2.03
2  130380.0        5.62
3  130381.0         NaN
4  130382.0         NaN

In [27]:
CRP.shape

(8727, 2)

In [28]:
smoking = datasets["SMQ_L"][["SEQN", "SMQ020", "SMQ040"]].rename(columns={"SEQN": "id", "SMQ020": "Smoked_100_cigs?", "SMQ040": "Smoker_now?"})
smoking.head()

         id  Smoked_100_cigs?  Smoker_now?
0  130378.0               1.0          3.0
1  130379.0               1.0          3.0
2  130380.0               2.0          NaN
3  130384.0               2.0          NaN
4  130385.0               2.0          NaN

In [29]:
cholesterol = datasets["TCHOL_L"][["SEQN", "LBDTCSI"]].rename(columns={"SEQN": "id", "LBDTCSI": "Total_Cholesterol (mmol/L)"})
cholesterol.head()

         id  Total_Cholesterol (mmol/L)
0  130378.0                        6.83
1  130379.0                        5.53
2  130380.0                        4.84
3  130386.0                        4.73
4  130387.0                        5.25

In [30]:
triglycerides = datasets["TRIGLY_L"][["SEQN", "LBDTRSI", "LBDLDLSI"]].rename(columns={"SEQN": "id", "LBDTRSI": "Triglycerides (mmol/L)"})
triglycerides.head()

         id  Triglycerides (mmol/L)  LBDLDLSI
0  130378.0                   1.727     4.862
1  130379.0                   0.971     3.543
2  130380.0                   4.234     1.629
3  130386.0                   1.603     2.819
4  130394.0                   0.644     3.207

In [31]:
triglycerides.shape

(3996, 3)

In [32]:
vitamin_d = datasets["VID_L"][["SEQN", "LBXVIDMS"]].rename(columns={"SEQN": "id", "LBXVIDMS": "Vitamin_D (nmol/L)"})
vitamin_d.head()

         id  Vitamin_D (nmol/L)
0  130378.0                58.9
1  130379.0                60.5
2  130380.0                39.4
3  130381.0                 NaN
4  130382.0                 NaN

In [33]:
vitamin_d.shape

(8727, 2)

In [34]:
demo.isna().sum()

id           0
gender       0
age          0
ethnicity    0
dtype: int64

In [35]:
haem = cbc.merge(ferritin, on="id", how="left")
haem = haem.merge(folate, on="id", how="left")
haem.head()

,id,WBC (Abs.),Lymphocytes (Abs.),Monocytes (Abs.),Neutrophils (Abs.),RBC,Haemoglobin (g/dL),HCT (%),MCV (fL),MCHC(g/dL),MCH(pg),RDW(%),PLT(1000/μL),MPV(fL),Ferritin (ng/mL),Folate (nmol/L)
0,130378.0,4.7,1.9,0.3,2.2,5.19,15.7,45.3,87.4,34.6,30.2,12.9,259.0,7.8,NaN,14.1
1,130379.0,6.3,1.6,0.9,3.6,4.59,15.2,43.9,95.8,34.5,33.0,12.8,221.0,8.5,NaN,24.3
2,130380.0,5.7,1.7,0.3,3.3,4.86,13.8,40.1,82.5,34.4,28.3,13.3,235.0,9.1,13.3,25.1
3,130381.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,130382.0,11.4,3.4,0.9,6.9,4.61,12.3,36.5,79.2,33.6,26.7,14.6,342.0,7.4,24.4,70.5

In [36]:
lifestyle = alcohol.merge(smoking, on="id", how="left")
lifestyle.head()

,id,Alc_consum?,Alc_<12M?,Avg_drink_day_12M,Days_+4_drinks,Days_+8_drinks?,Smoked_100_cigs?,Smoker_now?
0,130378.0,NaN,NaN,NaN,NaN,NaN,1.0,3.0
1,130379.0,1.0,2.000000e+00,3.0,5.397605e-79,NaN,1.0,3.0
2,130380.0,1.0,1.000000e+01,1.0,5.397605e-79,NaN,2.0,NaN
3,130386.0,1.0,4.000000e+00,2.0,1.000000e+01,10.0,1.0,3.0
4,130387.0,1.0,5.397605e-79,NaN,NaN,NaN,2.0,NaN

In [37]:
demo_body = demo.merge(BMI, on="id", how="left")
demo_body.head()

,id,gender,age,ethnicity,Weight (kg),Height (cm),BMI,Waist_Circumference (cm),Hip_Circumference (cm)
0,130378.0,1.0,43.0,6.0,86.9,179.5,27.0,98.3,102.9
1,130379.0,1.0,66.0,3.0,101.8,174.2,33.5,114.7,112.4
2,130380.0,2.0,44.0,2.0,69.4,152.9,29.7,93.5,98.0
3,130381.0,2.0,5.0,7.0,34.3,120.1,23.8,70.4,NaN
4,130382.0,1.0,2.0,3.0,13.6,NaN,NaN,NaN,NaN

In [38]:
lipids = cholesterol.merge(HDL, on="id", how="left")
lipids = lipids.merge(triglycerides, on="id", how="left")
lipids.head()

,id,Total_Cholesterol (mmol/L),HDL (mmol/L),Triglycerides (mmol/L),LBDLDLSI
0,130378.0,6.83,1.16,1.727,4.862
1,130379.0,5.53,1.55,0.971,3.543
2,130380.0,4.84,1.27,4.234,1.629
3,130386.0,4.73,1.19,1.603,2.819
4,130387.0,5.25,1.09,NaN,NaN

In [39]:
lipids = lipids.rename(columns={
    "LBDLDLSI": "LDL (mmol/L)"
})
lipids.head()

,id,Total_Cholesterol (mmol/L),HDL (mmol/L),Triglycerides (mmol/L),LDL (mmol/L)
0,130378.0,6.83,1.16,1.727,4.862
1,130379.0,5.53,1.55,0.971,3.543
2,130380.0,4.84,1.27,4.234,1.629
3,130386.0,4.73,1.19,1.603,2.819
4,130387.0,5.25,1.09,NaN,NaN

In [40]:
lipids = lipids[
    [
        "id",
        "Total_Cholesterol (mmol/L)",
        "LDL (mmol/L)",
        "HDL (mmol/L)",
        "Triglycerides (mmol/L)"
    ]
]

lipids.head()

,id,Total_Cholesterol (mmol/L),LDL (mmol/L),HDL (mmol/L),Triglycerides (mmol/L)
0,130378.0,6.83,4.862,1.16,1.727
1,130379.0,5.53,3.543,1.55,0.971
2,130380.0,4.84,1.629,1.27,4.234
3,130386.0,4.73,2.819,1.19,1.603
4,130387.0,5.25,NaN,1.09,NaN

In [41]:
biochemistry = biochem.merge(CRP, on="id", how="left")
biochemistry = biochemistry.merge(hba1c, on="id", how="left")
biochemistry = biochemistry.merge(vitamin_d, on="id", how="left")
biochemistry.head()

,id,ALT (IU/L),Albumin (g/L),AST (IU/L),Glucose (mmol/L),GGT (IU/L),Iron (μmol/L),Total_Bilirubin (μmol/L),Cholesterol (mmol/L),Total_Protein (g/L),Triglycerides (mmol/L),Uric_Acid (μmol/L),CRP (mg/L),HbA1c (%),Vitamin_D (nmol/L)
0,130378.0,39.0,43.0,25.0,6.0,41.0,18.0,0.7,6.89,75.0,1.73,303.3,1.78,5.6,58.9
1,130379.0,17.0,39.0,20.0,5.0,31.0,16.0,0.7,5.62,73.0,0.99,505.6,2.03,5.6,60.5
2,130380.0,13.0,37.0,15.0,8.0,44.0,24.0,0.6,4.74,76.0,4.24,261.7,5.62,6.2,39.4
3,130386.0,34.0,43.0,20.0,5.0,28.0,25.0,0.5,4.79,69.0,1.58,356.9,1.05,5.1,96.9
4,130387.0,12.0,37.0,13.0,6.0,17.0,8.0,0.3,5.26,67.0,1.25,368.8,3.96,5.9,26.7

In [42]:
BP_diabetes = blood_pressure.merge(diabetes, on="id", how="left")
BP_diabetes = bp_readings.merge(BP_diabetes, on="id", how="left")
BP_diabetes.head()

,id,Systolic_BP_1(mmHg),Diastolic_BP_1(mmHg),Systolic_BP_2(mmHg),Diastolic_BP_2(mmHg),Systolic_BP_3(mmHg),Diastolic_BP_3(mmHg),Pulse_1,Pulse_2,Pulse_3,Ever_told_high_BP?,BP_medication?,high_cholesterol?,cholesterol_medication?,Ever_told_diabetes?,Age_Diabetes,Ever_told_pre-diabetes?,Insulin?,Diabetes_medication?
0,130378.0,135.0,98.0,131.0,96.0,132.0,94.0,82.0,79.0,82.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN
1,130379.0,121.0,84.0,117.0,76.0,113.0,76.0,72.0,71.0,73.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN
2,130380.0,111.0,79.0,112.0,80.0,104.0,76.0,84.0,83.0,77.0,2.0,NaN,1.0,1.0,1.0,35.0,NaN,2.0,1.0
3,130386.0,110.0,72.0,120.0,74.0,115.0,75.0,59.0,64.0,64.0,2.0,NaN,2.0,2.0,2.0,NaN,2.0,NaN,NaN
4,130387.0,143.0,76.0,136.0,74.0,145.0,78.0,80.0,80.0,77.0,1.0,1.0,1.0,2.0,2.0,NaN,2.0,NaN,NaN

In [43]:
BP_diabetes["Mean_Systolic_BP"] = BP_diabetes[
    ["Systolic_BP_1(mmHg)", "Systolic_BP_2(mmHg)", "Systolic_BP_3(mmHg)"]
].mean(axis=1)

BP_diabetes["Mean_Diastolic_BP"] = BP_diabetes[
    ["Diastolic_BP_1(mmHg)", "Diastolic_BP_2(mmHg)", "Diastolic_BP_3(mmHg)"]
].mean(axis=1)

BP_diabetes["Mean_Pulse"] = BP_diabetes[
    ["Pulse_1", "Pulse_2", "Pulse_3"]
].mean(axis=1)

BP_diabetes.head()

,id,Systolic_BP_1(mmHg),Diastolic_BP_1(mmHg),Systolic_BP_2(mmHg),Diastolic_BP_2(mmHg),Systolic_BP_3(mmHg),Diastolic_BP_3(mmHg),Pulse_1,Pulse_2,Pulse_3,...,high_cholesterol?,cholesterol_medication?,Ever_told_diabetes?,Age_Diabetes,Ever_told_pre-diabetes?,Insulin?,Diabetes_medication?,Mean_Systolic_BP,Mean_Diastolic_BP,Mean_Pulse
0,130378.0,135.0,98.0,131.0,96.0,132.0,94.0,82.0,79.0,82.0,...,2.0,2.0,2.0,NaN,2.0,NaN,NaN,132.666667,96.000000,81.000000
1,130379.0,121.0,84.0,117.0,76.0,113.0,76.0,72.0,71.0,73.0,...,2.0,2.0,2.0,NaN,2.0,NaN,NaN,117.000000,78.666667,72.000000
2,130380.0,111.0,79.0,112.0,80.0,104.0,76.0,84.0,83.0,77.0,...,1.0,1.0,1.0,35.0,NaN,2.0,1.0,109.000000,78.333333,81.333333
3,130386.0,110.0,72.0,120.0,74.0,115.0,75.0,59.0,64.0,64.0,...,2.0,2.0,2.0,NaN,2.0,NaN,NaN,115.000000,73.666667,62.333333
4,130387.0,143.0,76.0,136.0,74.0,145.0,78.0,80.0,80.0,77.0,...,1.0,2.0,2.0,NaN,2.0,NaN,NaN,141.333333,76.000000,79.000000

In [44]:
drop = ["Systolic_BP_1(mmHg)", "Systolic_BP_2(mmHg)", "Systolic_BP_3(mmHg)", "Diastolic_BP_1(mmHg)", "Diastolic_BP_2(mmHg)", "Diastolic_BP_3(mmHg)", "Pulse_1", "Pulse_2", "Pulse_3"]
BP_diabetes = BP_diabetes.drop(columns=drop)
BP_diabetes.head()

,id,Ever_told_high_BP?,BP_medication?,high_cholesterol?,cholesterol_medication?,Ever_told_diabetes?,Age_Diabetes,Ever_told_pre-diabetes?,Insulin?,Diabetes_medication?,Mean_Systolic_BP,Mean_Diastolic_BP,Mean_Pulse
0,130378.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,132.666667,96.000000,81.000000
1,130379.0,1.0,1.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,117.000000,78.666667,72.000000
2,130380.0,2.0,NaN,1.0,1.0,1.0,35.0,NaN,2.0,1.0,109.000000,78.333333,81.333333
3,130386.0,2.0,NaN,2.0,2.0,2.0,NaN,2.0,NaN,NaN,115.000000,73.666667,62.333333
4,130387.0,1.0,1.0,1.0,2.0,2.0,NaN,2.0,NaN,NaN,141.333333,76.000000,79.000000

In [45]:
BP_diabetes = BP_diabetes[
    [
        "id",
        "Ever_told_high_BP?",
        "BP_medication?",
        "Mean_Systolic_BP",
        "Mean_Diastolic_BP",
        "Mean_Pulse",
        "high_cholesterol?",
        "cholesterol_medication?",
        "Ever_told_diabetes?",
        "Age_Diabetes",
        "Ever_told_pre-diabetes?",
        "Insulin?",
        "Diabetes_medication?"
    ]
]

BP_diabetes.head()

,id,Ever_told_high_BP?,BP_medication?,Mean_Systolic_BP,Mean_Diastolic_BP,Mean_Pulse,high_cholesterol?,cholesterol_medication?,Ever_told_diabetes?,Age_Diabetes,Ever_told_pre-diabetes?,Insulin?,Diabetes_medication?
0,130378.0,1.0,1.0,132.666667,96.000000,81.000000,2.0,2.0,2.0,NaN,2.0,NaN,NaN
1,130379.0,1.0,1.0,117.000000,78.666667,72.000000,2.0,2.0,2.0,NaN,2.0,NaN,NaN
2,130380.0,2.0,NaN,109.000000,78.333333,81.333333,1.0,1.0,1.0,35.0,NaN,2.0,1.0
3,130386.0,2.0,NaN,115.000000,73.666667,62.333333,2.0,2.0,2.0,NaN,2.0,NaN,NaN
4,130387.0,1.0,1.0,141.333333,76.000000,79.000000,1.0,2.0,2.0,NaN,2.0,NaN,NaN

In [46]:
df = demo_body.merge(haem, on="id", how="left")
df = df.merge(lifestyle, on="id", how="left")
df = df.merge(BP_diabetes, on="id", how="left")
df = df.merge(biochemistry, on="id", how="left")
df = df.merge(lipids, on="id", how="left")

In [47]:
df.to_csv("../data/processed/analytical_dataset.csv", index=False)

In [48]:
import pandas as pd

df = pd.read_csv("../data/processed/analytical_dataset.csv")

In [49]:
df.columns

Index(['id', 'gender', 'age', 'ethnicity', 'Weight (kg)', 'Height (cm)', 'BMI',
       'Waist_Circumference (cm)', 'Hip_Circumference (cm)', 'WBC (Abs.)',
       'Lymphocytes (Abs.)', 'Monocytes (Abs.)', 'Neutrophils (Abs.)', 'RBC',
       'Haemoglobin (g/dL)', 'HCT (%)', 'MCV (fL)', 'MCHC(g/dL)', 'MCH(pg)',
       'RDW(%)', 'PLT(1000/μL)', 'MPV(fL)', 'Ferritin (ng/mL)',
       'Folate (nmol/L)', 'Alc_consum?', 'Alc_<12M?', 'Avg_drink_day_12M',
       'Days_+4_drinks', 'Days_+8_drinks?', 'Smoked_100_cigs?', 'Smoker_now?',
       'Ever_told_high_BP?', 'BP_medication?', 'Mean_Systolic_BP',
       'Mean_Diastolic_BP', 'Mean_Pulse', 'high_cholesterol?',
       'cholesterol_medication?', 'Ever_told_diabetes?', 'Age_Diabetes',
       'Ever_told_pre-diabetes?', 'Insulin?', 'Diabetes_medication?',
       'ALT (IU/L)', 'Albumin (g/L)', 'AST (IU/L)', 'Glucose (mmol/L)',
       'GGT (IU/L)', 'Iron (μmol/L)', 'Total_Bilirubin (μmol/L)',
       'Cholesterol (mmol/L)', 'Total_Protein (g/L)',
       'Triglycerides (mmol/L)_x', 'Uric_Acid (μmol/L)', 'CRP (mg/L)',
       'HbA1c (%)', 'Vitamin_D (nmol/L)', 'Total_Cholesterol (mmol/L)',
       'LDL (mmol/L)', 'HDL (mmol/L)', 'Triglycerides (mmol/L)_y'],
      dtype='str')

In [50]:
df.rename(columns={'Triglycerides (mmol/L)_y': 'Triglycerides (mmol/L)'}, inplace=True)

In [51]:
df.columns = (
    df.columns
    .str.lower()
    .str.replace(" ", "_")
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
)
df.columns

Index(['id', 'gender', 'age', 'ethnicity', 'weight_kg', 'height_cm', 'bmi',
       'waist_circumference_cm', 'hip_circumference_cm', 'wbc_abs.',
       'lymphocytes_abs.', 'monocytes_abs.', 'neutrophils_abs.', 'rbc',
       'haemoglobin_g/dl', 'hct_%', 'mcv_fl', 'mchcg/dl', 'mchpg', 'rdw%',
       'plt1000/μl', 'mpvfl', 'ferritin_ng/ml', 'folate_nmol/l', 'alc_consum?',
       'alc_<12m?', 'avg_drink_day_12m', 'days_+4_drinks', 'days_+8_drinks?',
       'smoked_100_cigs?', 'smoker_now?', 'ever_told_high_bp?',
       'bp_medication?', 'mean_systolic_bp', 'mean_diastolic_bp', 'mean_pulse',
       'high_cholesterol?', 'cholesterol_medication?', 'ever_told_diabetes?',
       'age_diabetes', 'ever_told_pre-diabetes?', 'insulin?',
       'diabetes_medication?', 'alt_iu/l', 'albumin_g/l', 'ast_iu/l',
       'glucose_mmol/l', 'ggt_iu/l', 'iron_μmol/l', 'total_bilirubin_μmol/l',
       'cholesterol_mmol/l', 'total_protein_g/l', 'triglycerides_mmol/l_x',
       'uric_acid_μmol/l', 'crp_mg/l', 'hba1c_%', 'vitamin_d_nmol/l',
       'total_cholesterol_mmol/l', 'ldl_mmol/l', 'hdl_mmol/l',
       'triglycerides_mmol/l'],
      dtype='str')

In [52]:
df.drop(columns=["triglycerides_mmol/l_x"], inplace=True)

In [53]:
df.rename(columns={'ever_told_diabetes?': 'diabetes?'}, inplace=True)
df.rename(columns={'ever_told_pre-diabetes?': 'pre_diabetes?'}, inplace=True)
df.rename(columns={'ever_told_high_bp?': 'high_bp?'}, inplace=True)

In [54]:
df.drop(columns=["days_+4_drinks", "days_+8_drinks?"], inplace=True)

In [55]:
df["haemoglobin_mmol/l"] = df["haemoglobin_g/dl"] / 1.611

In [56]:
df.drop(columns=["haemoglobin_g/dl"], inplace=True)
df.insert(
    loc=14,
    column="haemoglobin_mmol/l",
    value=df.pop("haemoglobin_mmol/l")
)

In [57]:
df.drop(columns=["age_diabetes"], inplace=True)

In [58]:
#create new columns for waist-hip ratio and neutrophil-lymphocyte ratio

df["waist_hip_ratio"] = (
    df["waist_circumference_cm"] /
    df["hip_circumference_cm"]
)

df.insert(
    loc=9,
    column="waist_hip_ratio",
    value=df.pop("waist_hip_ratio")
)

df["nlr"] = (
    df["neutrophils_abs."] /
    df["lymphocytes_abs."]
)

df.insert(
    loc=13,
    column="nlr",
    value=df.pop("nlr")
)

df["non_hdl_mmol_l"] = (
    df["total_cholesterol_mmol/l"] -
    df["hdl_mmol/l"]
)

In [59]:
df.columns

Index(['id', 'gender', 'age', 'ethnicity', 'weight_kg', 'height_cm', 'bmi',
       'waist_circumference_cm', 'hip_circumference_cm', 'waist_hip_ratio',
       'wbc_abs.', 'lymphocytes_abs.', 'monocytes_abs.', 'nlr',
       'neutrophils_abs.', 'rbc', 'haemoglobin_mmol/l', 'hct_%', 'mcv_fl',
       'mchcg/dl', 'mchpg', 'rdw%', 'plt1000/μl', 'mpvfl', 'ferritin_ng/ml',
       'folate_nmol/l', 'alc_consum?', 'alc_<12m?', 'avg_drink_day_12m',
       'smoked_100_cigs?', 'smoker_now?', 'high_bp?', 'bp_medication?',
       'mean_systolic_bp', 'mean_diastolic_bp', 'mean_pulse',
       'high_cholesterol?', 'cholesterol_medication?', 'diabetes?',
       'pre_diabetes?', 'insulin?', 'diabetes_medication?', 'alt_iu/l',
       'albumin_g/l', 'ast_iu/l', 'glucose_mmol/l', 'ggt_iu/l', 'iron_μmol/l',
       'total_bilirubin_μmol/l', 'cholesterol_mmol/l', 'total_protein_g/l',
       'uric_acid_μmol/l', 'crp_mg/l', 'hba1c_%', 'vitamin_d_nmol/l',
       'total_cholesterol_mmol/l', 'ldl_mmol/l', 'hdl_mmol/l',
       'triglycerides_mmol/l', 'non_hdl_mmol_l'],
      dtype='str')

In [60]:
df = df[df["age"] >= 18]
df = df.reset_index(drop=True)

# 📋 Data Dictionary

| Variable                | Type        | Description                                                                  |
| ----------------------- | ----------- | ---------------------------------------------------------------------------- |
| age                     | Numeric     | Participant age in years                                                     |
| gender                  | Categorical | Participant sex (Male/Female)                                                |
| bmi                     | Numeric     | Body Mass Index (kg/m²)                                                      |
| waist_circumference_cm  | Numeric     | Waist circumference in centimetres                                           |
| waist_hip_ratio         | Numeric     | Waist circumference divided by hip circumference                             |
| smoking_status          | Categorical | Smoking classification (Never, Former, Current Some Days, Current Every Day) |
| smoking_score           | Ordinal     | Numerical smoking intensity score (0–3)                                      |
| alcohol_frequency_group | Categorical | Alcohol consumption frequency category                                       |
| alcohol_frequency_score | Ordinal     | Numerical alcohol frequency score                                            |
| avg_drinks_per_day      | Numeric     | Average alcoholic drinks consumed per drinking day                           |
| systolic_bp_mean        | Numeric     | Mean systolic blood pressure                                                 |
| diastolic_bp_mean       | Numeric     | Mean diastolic blood pressure                                                |
| pulse_mean              | Numeric     | Mean pulse rate                                                              |
| hba1c_%                 | Numeric     | Glycated haemoglobin (%)                                                     |
| glucose_mmol/l          | Numeric     | Blood glucose concentration                                                  |
| triglycerides_mmol/l    | Numeric     | Triglyceride concentration                                                   |
| hdl_mmol/l              | Numeric     | HDL cholesterol concentration                                                |
| ldl_mmol/l              | Numeric     | LDL cholesterol concentration                                                |
| non_hdl_mmol/l          | Numeric     | Non-HDL cholesterol concentration                                            |
| crp_mg/l                | Numeric     | High-sensitivity C-reactive protein                                          |
| log_crp                 | Numeric     | Log-transformed CRP value                                                    |
| high_crp                | Binary      | Elevated CRP classification (0 = Normal, 1 = Elevated)                       |
| ferritin_ug/l           | Numeric     | Ferritin concentration                                                       |
| vitamin_d_nmol/l        | Numeric     | Vitamin D concentration                                                      |
| folate_ng/ml            | Numeric     | Serum folate concentration                                                   |
| wbc_abs.                | Numeric     | White blood cell count                                                       |
| neutrophils_abs.        | Numeric     | Absolute neutrophil count                                                    |
| lymphocytes_abs.        | Numeric     | Absolute lymphocyte count                                                    |
| monocytes_abs.          | Numeric     | Absolute monocyte count                                                      |
| nlr                     | Numeric     | Neutrophil-to-lymphocyte ratio                                               |
| haemoglobin_mmol/l      | Numeric     | Haemoglobin concentration                                                    |
| hct_%                   | Numeric     | Haematocrit (%)                                                              |
| mcv_fl                  | Numeric     | Mean Cell Volume                                                             |
| mchc_g/dl               | Numeric     | Mean Cell Haemoglobin Concentration                                          |
| platelets_abs.          | Numeric     | Platelet count                                                               |
| alt_u/l                 | Numeric     | Alanine aminotransferase                                                     |
| ast_u/l                 | Numeric     | Aspartate aminotransferase                                                   |
| ggt_u/l                 | Numeric     | Gamma-glutamyl transferase                                                   |
| hba1c_group             | Categorical | Normal, Prediabetes or Diabetes classification                               |
| cluster                 | Categorical | K-Means participant phenotype assignment                                     |
| PC1                     | Numeric     | First principal component score                                              |
| PC2                     | Numeric     | Second principal component score                                             |

In [61]:
df.to_csv("../data/processed/analytical_dataset.csv", index=False)